/* Generated By:JavaCC: Do not edit this line. QueryParserConstants.java */
package edu.ucsd.grammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KWFOR = 5;
  /** RegularExpression Id. */
  int KWWHERE = 6;
  /** RegularExpression Id. */
  int KWRETURN = 7;
  /** RegularExpression Id. */
  int LETTER = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;
  /** RegularExpression Id. */
  int WORD_CONTEXT = 10;
  /** RegularExpression Id. */
  int WORD = 11;
  /** RegularExpression Id. */
  int DOC_AND_SENTENCE_FUNCTION = 12;
  /** RegularExpression Id. */
  int FUNCTION = 13;
  /** RegularExpression Id. */
  int WHERE_CLAUSE_CONNECTOR = 14;
  /** RegularExpression Id. */
  int NOT = 15;
  /** RegularExpression Id. */
  int IDENTIFIER_TYPES = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;
  /** RegularExpression Id. */
  int IDENTIFIER_TYPE_SEPARATOR = 18;
  /** RegularExpression Id. */
  int VARIABLE_ASSIGNMENT = 19;
  /** RegularExpression Id. */
  int OPEN_PAR = 20;
  /** RegularExpression Id. */
  int CLOSE_PAR = 21;
  /** RegularExpression Id. */
  int CLAUSE_SEPARATOR = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"for\"",
    "\"where\"",
    "\"return\"",
    "<LETTER>",
    "<DIGIT>",
    "<WORD_CONTEXT>",
    "<WORD>",
    "<DOC_AND_SENTENCE_FUNCTION>",
    "<FUNCTION>",
    "<WHERE_CLAUSE_CONNECTOR>",
    "\"not\"",
    "<IDENTIFIER_TYPES>",
    "<IDENTIFIER>",
    "\":\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
